#!/bin/sh
set -eu

usage() {
	echo 'usage: build [debug|release] target...' 1>&2
	exit 1
}

debug=1
targets=''
opt='-O3'
common='-I../ -g -fdiagnostics-absolute-paths -Wall -Wextra'
medialibs='-lavcodec -lavformat -lavutil -lswscale'

for i
do
	case "$i" in
	debug)
		debug=1
		;;
	release)
		debug=0
		;;
	mediasrv|tor|tordl|torrss)
		targets="$targets $i"
		;;
	*)
		usage
		;;
	esac
done

[ -z "$targets" ] && usage
[ "$debug" -eq 1 ] && opt='-O0 -fsanitize=address -fno-omit-frame-pointer'
cc="clang $opt $common"
cpp="clang++ $opt $common"

mkdir -p bin
cd bin || exit 1
for t in $targets
do
	case "$t" in
	mediasrv)
		$cc ../cmd/mediasrv/main.c $medialibs -o mediasrv
		;;
	tor)
		torlibs="$(pkg-config --cflags --libs libxml-2.0) -lcurl"
		$cc ../cmd/tor/main.c $torlibs -o tor
		;;
	tordl)
		torlibs="$(pkg-config --cflags --libs libtorrent-rasterbar)"
		$cpp ../cmd/tordl/main.cpp $torlibs -o tordl
		;;
	torrss)
		torlibs="$(pkg-config --cflags --libs libxml-2.0 libtorrent-rasterbar) -lcurl"
		$cpp ../cmd/torrss/main.cpp $torlibs -o torrss
		;;
	esac
done

cd ..
