#!/bin/sh
set -e

ln -sf "$PWD/.gitconfig" "$HOME/.gitconfig"

mkdir -p "$HOME/.config"
if [[ "$(uname)" == 'Darwin' ]]; then
  ln -sf "$PWD/kitty" "$HOME/.config"
fi
ln -sf "$PWD/nvim" "$HOME/.config"

