#!/bin/sh
ln -sf "$PWD/zshrc" "$HOME/.zshrc"

mkdir -p "$HOME/bin" || true
ln -sf "$PWD/bin/"* "$HOME/bin"

# Call subsequent setup scripts for other configurations
for i in vim; do
    cd $i && ./setup
    cd -
done

chsh -s $(which zsh)
