# Do not modify this file! It was generated by `nixos-generate-config`
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];
  boot = {
    initrd = {
      availableKernelModules = ["ahci" "nvme" "sd_mod" "usbhid" "usb_storage" "xhci_pci"];
      kernelModules = ["amdgpu"];
    };
    kernelModules = ["kvm-amd"];
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2e39b17a-a5ab-4473-a6e2-9fc98ab21590";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/9A48-64F0";
      fsType = "vfat";
    };
  };
  hardware = {
    cpu.amd.updateMicrocode = config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      enable32Bit = true;
    };
  };
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = "x86_64-linux";
  powerManagement.cpuFreqGovernor = "performance";
}
