if has("eval")
    let skip_defaults_vim=1
endif

set nocompatible
set noerrorbells
set autoindent
set autowrite
set number
set ruler
set relativenumber
set tabstop=4 softtabstop=4 shiftwidth=4
set smartindent
set smarttab
set expandtab
set hlsearch
set incsearch
set wrapscan
set textwidth=72
set linebreak
set nobackup
set noswapfile
set nowritebackup
set icon
set viminfo='20,<1000,s1000
set noshowmatch
set wildmenu
set hidden
set history=100
set ttyfast
set updatetime=300
set background=dark
filetype plugin indent on
syntax on

let mapleader=" "

" Mark trailing spaces as errors
match IncSearch '\s\+$'

" Make Y consitent with D and C (yank til end)
map Y y$

" Start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Functions keys
map <F1> :set number!<CR> :set relativenumber!<CR>
set pastetoggle=<F2>
map <F3> :set list!<CR>
map <F4> :set cursorline!<CR>
map <F5> :set spell!<CR>

" Better use of arrow keys, number increment/decrement
nnoremap <up> <C-a>
nnoremap <down> <C-x>

