" Mark trailing spaces as errors
match ErrorMsg '\s\+$'

" Make Y consitent with D and C (yank til end)
map Y y$

" Start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Functions keys
map <F1> :set number!<CR> :set relativenumber!<CR>
set pastetoggle=<F2>
map <F3> :set list!<CR>
map <F4> :set cursorline!<CR>
map <F5> :set spell!<CR>
map <F6> :set fdm=indent<CR>

" Other Configurations
let skip_defaults_vim=1
set nocompatible
set autoindent
set autowrite
set encoding=utf-8
set exrc
set ruler
set relativenumber
set nu
set hidden
set noerrorbells
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab
set smartindent
set smarttab
set icon
set nowrap
set smartcase
set incsearch
set hlsearch
set linebreak
set viminfo='20,<1000,s1000
set termguicolors
set scrolloff=8
set colorcolumn=80
set showmatch
set wildmode=longest,list
set cmdheight=2
set updatetime=300
set ttyfast
filetype plugin indent on
syntax on
