#!/usr/bin/env bash
send_email() {
    local body="$1"
    mail -s 'BTRFS Failure' root <<< "${body}"
    exit 0
}

drives=(/dev/sda /dev/sdb /dev/sdc /dev/sdd)
if stats="$(btrfs device stats --check /media)"; then
    for drive in "${drives[@]}"; do
        if ! grep -q "$drive" <<< "$stats"; then
            send_email "${stats}"
        fi
    done
else
    send_email "${stats}"
fi