local dap, dapgo, dapui = require("dap"), require("dap-go"), require("dapui")
vim.keymap.set("n", "<F1>", dap.step_back)
vim.keymap.set("n", "<F2>", dap.step_into)
vim.keymap.set("n", "<F3>", dap.step_over)
vim.keymap.set("n", "<F4>", dap.step_out)
vim.keymap.set("n", "<F5>", dap.continue)
vim.keymap.set("n", "<leader>db", dap.toggle_breakpoint)
vim.keymap.set("n", "<leader>dB", function()
    dap.set_breakpoint(vim.fn.input "[DAP] Condition > ")
end)
vim.keymap.set("n", "<leader>de", dapui.eval)
vim.keymap.set("n", "<leader>dE", function()
    dapui.eval(vim.fn.input "[DAP] Expression > ")
end)
vim.keymap.set("n", "<leader>dr", dap.repl.open)
vim.keymap.set("n", "<leader>dt", dapgo.debug_test)
